### ISSUE TITLE
macosx证书如何导入qt中

### ISSUE THREAD

**Issue by modonglinaguadu** [FanghuaGuo/L2tpDialMac#1]
我开发一个personal vpn osx桌面应用，可是打包应用的时候遇到了问题，看到楼主的项目，所以来请教楼主，望楼主能指点迷津
开发vpn需要有开发者账号，而且开启Network Extensions框架和Personal Vpn框架，并且创建对应的Provisioning Profiles文件，但是在qt中，我找了很久也没找到如何导入appid和证书等相关信息，不知道楼主是如何解决该问题的。
我也使用过“qmake -spec macx-xcode”的方式生成xcode项目，在Xcode的general中确实能填写证书等信息，并且使应用运行成功，但是从xcode打包又遇到了问题，使用macdeployqt指令导入相关framework和插件，但是程序就无法打开了。

**Comment by qiyugfh** [comment]
很抱歉，这个问题我也不清楚
